import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import {
  faParking,
  faCalendarCheck,
  faUserCircle,
  faCog,
  faUser,
  faCircleQuestion,
  faInfoCircle,
  faRightFromBracket,
  faRightToBracket,
  faCreditCard,
  faSearch,
  faCheckCircle,
  faCashRegister,
  faLaptop,
  faArrowRight,
  faEraser,
  faPaperPlane,
  faChartLine,
  faShieldAlt,
  faSave,
  faPlus,
  faTrash,
  faChevronDown,
  faWallet,
  faReceipt,
  faTimesCircle,
  faXmark,
  faCheck,
  faLocationDot,
  faPenToSquare,
} from "@fortawesome/free-solid-svg-icons";

import { faApple, faAndroid } from "@fortawesome/free-brands-svg-icons";

library.add(
  faParking,
  faCalendarCheck,
  faRightToBracket,
  faUserCircle,
  faCog,
  faInfoCircle,
  faUser,
  faCircleQuestion,
  faRightFromBracket,
  faCreditCard,
  faApple,
  faAndroid,
  faSearch,
  faCheckCircle,
  faCashRegister,
  faLaptop,
  faArrowRight,
  faEraser,
  faPaperPlane,
  faShieldAlt,
  faChartLine,
  faSave,
  faPlus,
  faTrash,
  faChevronDown,
  faWallet,
  faReceipt,
  faTimesCircle,
  faXmark,
  faCheck,
  faLocationDot,
  faCheck,
  faPenToSquare
);

export { FontAwesomeIcon };
